nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/login/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']
        '^/user/':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST' ]
            max_age: 3600
            hosts: [ '^api\.' ]
        '^/users/':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'GET' ]
            max_age: 3600
            hosts: [ '^api\.' ]
        '^/user/{id}':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'GET' ]
            max_age: 3600
            hosts: [ '^api\.' ]
        '^/region/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST','DELETE' ]
            max_age: 3600
            hosts: [ '^api\.' ]
        '^/regions/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'GET','POST' ]
            max_age: 3600
            hosts: [ '^api\.' ]
        '^/region/{id}/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST' ]
            max_age: 3600
            hosts: [ '^api\.' ]
