security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    memory_database_users:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    korv_login:
      pattern: ^/login
      stateless: true
      json_login:
        check_path: /login
    api:
      pattern: ^/
      stateless: true
      jwt:
        ~

  access_control:
    - { path: ^/login,           roles: PUBLIC_ACCESS }
    - { path: ^/user,            roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/user/:id,        roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/user/:id/status, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/users,           roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/region,          roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/region/:id,      roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/regions,         roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/local,           roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/local/:id,       roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/locals,          roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/sensor,          roles: IS_AUTHENTICATED_FULLY }
