security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    memory_database_users:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    korv_login:
      json_login:
        check_path: /login

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register,        roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/region,          roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/region/:id,      roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/regions,         roles: IS_AUTHENTICATED_FULLY }
