controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

korv_login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: POST

korv_logout:
  path: /logout
  controller: App\Controller\LoginController::logout
  methods: POST

api_login_check:
  path: /api/login_check

dashboard_check:
  path: /dashboard

korv_user_create:
  path: /user
  controller: App\Controller\UserController::postUser
  methods: POST

korv_user_get:
  path: /users
  controller: App\Controller\UserController::getUsers
  methods: GET

korv_user_get_with_id:
  path: /user/{id}
  controller: App\Controller\UserController::getUserWithId
  methods: GET

korv_user_put:
    path: /user/{id}
    controller: App\Controller\UserController::putUser
    methods: PUT

korv_user_put_status:
    path: /user/{id}/status
    controller: App\Controller\UserController::putUserStatus
    methods: PUT

korv_region_create:
  path: /region
  controller: App\Controller\RegionController::postRegion
  methods: POST

korv_region_put:
  path: /region/{id}
  controller: App\Controller\RegionController::putRegion
  methods: PUT

korv_region_get:
  path: /regions
  controller: App\Controller\RegionController::getRegion
  methods: GET

korv_region_get_with_id:
  path: /region/{id}
  controller: App\Controller\RegionController::getRegionWithId
  methods: GET

korv_region_delete:
  path: /region
  controller: App\Controller\RegionController::deleteRegion
  methods: DELETE

korv_local_create:
  path: /local
  controller: App\Controller\LocalController::postLocal
  methods: POST


