<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container733CPE1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container733CPE1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container733CPE1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container733CPE1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container733CPE1\App_KernelDevDebugContainer([
    'container.build_hash' => '733CPE1',
    'container.build_id' => '014f8bdb',
    'container.build_time' => 1694578176,
], __DIR__.\DIRECTORY_SEPARATOR.'Container733CPE1');
